silver-octo/silver-octo/Controllers/Api/BudgetItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using silver_octo.Models;
using silver_octo.Data;
using System.Security.Claims;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace silver_octo.Controllers.Api
{
    [Route("api/BudgetItems")]
    public class BudgetItemsController : ControllerBase
    {
        private ApplicationDbContext _context;

        public BudgetItemsController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpGet]
        public IEnumerable<BudgetItem> GetBudgetItems()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return _context.BudgetItems.Where(b => b.ApplicationUserId == userId).ToList();
        }

        [HttpGet("{id}")]
        public IActionResult GetBudgetItem(long id)
        {
            var budgetItem = _context.BudgetItems.SingleOrDefault(b => b.Id == id);

            if (budgetItem == null)
            {
                return NotFound();
            }
            return Ok(budgetItem);
        }

        // POST api/values
        [HttpPost]
        public IActionResult CreateBudgetItem([FromBody]BudgetItem budgetItem)
        {
            budgetItem.DateCreated = DateTime.Now;
            budgetItem.DateUpdated = DateTime.Now;

            if (ModelState.IsValid)
            {
                _context.BudgetItems.Add(budgetItem);
                _context.SaveChanges();

                return Created("api/BudgetItems/" + budgetItem.Id, budgetItem);
            }

            return BadRequest();
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void UpdateBudgetItem(long id, BudgetItem budgetItem)
        {
            budgetItem.DateUpdated = DateTime.Now;

            if (!ModelState.IsValid) throw new Exception();

            var budgetItemInDb = _context.BudgetItems.SingleOrDefault(b => b.Id == id);

            if (budgetItemInDb == null) throw new Exception();

            budgetItemInDb.Amount = budgetItem.Amount;
            budgetItemInDb.CategoryName = budgetItem.CategoryName;
            budgetItemInDb.DateUpdated = budgetItem.DateUpdated;
            budgetItemInDb.Description = budgetItem.Description;

            _context.SaveChanges();
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void DeleteBudgetItem(long id)
        {
            if (!ModelState.IsValid) throw new Exception();

            var budgetItemInDb = _context.BudgetItems.SingleOrDefault(b => b.Id == id);

            if (budgetItemInDb == null) throw new Exception();

            _context.BudgetItems.Remove(budgetItemInDb);
            _context.SaveChanges();
        }
    }
}

silver-octo/silver-octo/Controllers/Api/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using silver_octo.Models;
using silver_octo.Data;
using System.Security.Claims;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace silver_octo.Controllers.Api
{
    [Route("api/Expenses")]
    public class ExpensesController : ControllerBase
    {

        private ApplicationDbContext _context;

        public ExpensesController()
        {
            this._context = new ApplicationDbContext();
        }

        [HttpGet]
        public IActionResult GetExpenses()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var expenses = _context.Expenses
                .Where(e => e.ApplicationUserId == userId)
                .Include(e => e.BudgetItem)
                .ToList();

            return Ok(expenses);
        }

        [HttpGet("{id}")]
        public IActionResult GetExpense(long id)
        {
            var expense = _context.Expenses.SingleOrDefault(e => e.Id == id);

            if (expense == null)
            {
                return NotFound();
            }
            return Ok(expense);
        }

        [HttpPost]
        public IActionResult CreateExpense([FromBody]Expense expense)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            expense.ApplicationUserId = userId;

            if (ModelState.IsValid)
            {
                expense.EntryDate = DateTime.Now;
                expense.ExpenseDate = DateTime.Now.Date;

                _context.Expenses.Add(expense);
                _context.SaveChanges();

                return Created("api/Expenses/" + expense.Id, expense);
            }

            return BadRequest();
        }

        [HttpPut("{id}")]
        public void UpdateExpense(long id, Expense expense)
        {
            if (!ModelState.IsValid) throw new Exception();

            var expenseInDb = _context.Expenses.SingleOrDefault(e => e.Id == id);

            if (expenseInDb == null) throw new Exception();

            expenseInDb.Name = expense.Name;
            expenseInDb.ExpenseDate = expense.ExpenseDate;
            expenseInDb.ExpenseAmount = expense.ExpenseAmount;
            expenseInDb.BudgetItemId = expense.BudgetItemId;


            _context.SaveChanges();
        }

        [HttpDelete("{id}")]
        public void DeleteExpense(long id)
        {
            if (!ModelState.IsValid) throw new Exception();

            var expenseInDb = _context.Expenses.SingleOrDefault(e => e.Id == id);

            if (expenseInDb == null) throw new Exception();

            _context.Expenses.Remove(expenseInDb);

            _context.SaveChanges();
        }
    }
}

silver-octo/silver-octo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - silver_octo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">silver_octo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BudgetItems" asp-action="Index">Budget Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - silver_octo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootbox/bootbox.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

silver-octo/silver-octo/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Silver-Octo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="BudgetItems" asp-action="Index">Budget Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>